Fixed some small mounting bugs

diff --git a/install-usb b/install-usb
--- a/install-usb
+++ b/install-usb
@@ -131,16 +131,31 @@ function unmount {
 #function does not check "devices" it instead calls the unmount
 #function using mount points.
 function unmount_all {
+    unmount $CHROOT/tmp
+    unmount $CHROOT/dev/pts
+    unmount $CHROOT/dev
     unmount $CHROOT/sys
     unmount $CHROOT/proc
-    unmount $CHROOT/dev
-    unmount $CHROOT/tmp
 
     if [[ ! -z "$MNT" ]] ; then
         unmount "$MNT"
         rmdir -v "$MNT" #MNT is a mktemp directory so get rid of it
     fi
 }
+
+function mount_all {
+
+    info "Mounting the needed directories under $CHROOT"
+    if ! (mount -vt proc proc "$CHROOT/proc"    &&
+          mount -vt tmpfs tmpfs "$CHROOT/tmp"   &&
+          mount -v --rbind /sys "$CHROOT/sys"   &&
+          mount -v --rbind /dev "$CHROOT/dev"   &&
+          mount -v --rbind /dev/pts "$CHROOT/dev/pts") ; then
+        die 'A mount failed!'
+    fi
+}
+
+
 
 #See if we are the root user
 if [[ "$UID" != "0" ]] ; then
@@ -374,14 +389,6 @@ trap "{ umount -lv /proc /sys /tmp /dev; exit 255 }" SIGINT SIGTERM
 info "Setting local time"
 ln -svf /usr/share/zoneinfo/US/Central /etc/localtime
 
-info "Mounting the needed directories under $CHROOT"
-if ! (mount -vt proc proc /proc  &&
-      mount -vt sysfs sysfs /sys &&
-      mount -vt tmpfs tmpfs /tmp &&
-      mount -vt devtmpfs udev /dev ) ; then
-    die 'A mount failed!'
-fi
-
 info 'Setting up the root user'
 groupadd admin
 usermod -a -G 'users,plugdev,audio,cdrom,admin,disk' root
@@ -413,7 +420,7 @@ info "Installing Virtualbox's Guest Additions"
 wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add - && apt-get update && apt-get -y install virtualbox-guest-utils
 
 #Try installing the WIM tools
-info "Installing WIM tools
+info "Installing WIM tools"
 if ! add-apt-repository -y ppa:nilarimogard/webupd8 && apt-get update && sudo apt-get install wimtools ; then
     die "Failed to install WIM tools"
 fi
@@ -441,9 +448,6 @@ fi
 info "Making root own /root"
 chown -R root:root /root
 
-info "Unmounting everthing"
-umount -lv /proc /sys /tmp /dev
-
 #Make mingetty auto-login on tty1
 sed 's|^exec.*$|exec /sbin/mingetty --autologin root --noclear tty1|' -i /etc/init/tty1.conf
 
@@ -454,6 +458,9 @@ then
     die "Could not create the script that manages the chroot install."
 fi
 
+info "Mounting needed filesystems before chroot"
+mount_all
+
 #Make the install script executable
 if ! chmod u+x $CHROOT/chroot-install ; then
     die "Could not make the chroot install script executable."
@@ -463,6 +470,9 @@ info 'Performing chroot install ...'
 if ! LANG=C chroot $CHROOT /chroot-install ; then
     die "Chroot install failed!"
 fi
+
+info "Unmount filesystems after chroot"
+unmount_all
 
 #For some reason the chroot changes the host environment's hostname
 #value. This is to change it back.
@@ -632,13 +642,8 @@ else
     #This is where we are going to mount $USB
     MNT=$(mktemp -d)
 
-    info "Mounting pseudo-filesystems"
-    if ! (mount -vt proc proc $CHROOT/proc  &&
-          mount -vt sysfs sysfs $CHROOT/sys &&
-          mount -vt tmpfs tmpfs $CHROOT/tmp &&
-          mount -vt devtmpfs udev $CHROOT/dev ) ; then
-        die 'A mount failed!'
-    fi
+    info "Mounting needed filesystems"
+    mount_all
 
     info "Mounting $USB at $MNT"
     if ! mount -v -t ext3 $USB $MNT ; then
